name: Build Home Assistant Installer
on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Download HA deb
      run: | 
        url="https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb"
        curl -L -o homeassistant-supervised.deb $url

    - name: Modify contents  
      run: |
        ar x homeassistant-supervised.deb
        FILES=$(tar Jxvf control.tar.xz)
        
        contents=$(cat control.txt)
        contents=$(echo "$contents" | sed 's/systemd-resolved//g')  
        echo "$contents" > control.txt
        
        tar Jcf control.tar.xz $FILES
        ar rcs homeassistant-modified.deb debian-binary control.tar.xz data.tar.xz

    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./homeassistant-modified.deb
        asset_name: homeassistant-modified.deb
        asset_content_type: application/vnd.debian.binary-package