name: Build Home Assistant Installer 

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Download HA deb
      run: |
        url="https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb"
        curl -L -o homeassistant-supervised.deb $url

    - name: Modify contents
      run: |
        ar x homeassistant-supervised.deb
        FILES=$(tar Jxvf control.tar.xz)
        sed -i '/systemd-resolved/d' control
        tar Jcf control.tar.xz $FILES  
        ar rcs homeassistant-modified.deb debian-binary control.tar.xz data.tar.xz

    - name: Upload deb artifact
      uses: actions/upload-artifact@v2
      with:
        name: homeassistant-modified.deb
        path: homeassistant-modified.deb

    - name: Get current version
      id: get_version
      run: |
        version=$(curl -s https://github.com/home-assistant/supervised-installer/releases/latest | grep -o "tag/.*\"" | cut -d/ -f3 | tr -d \")
        echo ::set-output name=version::${version}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        files: homeassistant-modified.deb