name: Version Test

on:
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest release
      id: get_latest_release
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/home-assistant/supervised-installer/releases/latest
        
    - name: Extract version
      id: extract_version  
      run: |
        VERSION=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
        VERSION=${VERSION#v}
        echo "::set-output name=version::$VERSION"
        
    - name: Print version
      run: echo ${{ steps.extract_version.outputs.version }}